# Generated by Django 4.1.7 on 2023-03-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donations_user_alter_profile_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
